### ISSUE TITLE
No alert error shown on top of Registration page, field error messages are different 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozillians#2057]
STR:
1. Login to mozillians with a new email -> registration page is shown
2. On Registration page, leave all fields empty and click "Complete Registration"

Expected:
Error message displayed on top of the page ("Please correct the errors below. "), inline error messages for all required fields left empty is shown

Actual:
No error message shown on top of the page, inline input field error message shown only for the first empty field.

**Comment by johngian** [comment]
This is supposed to be a feature. We went from Django 1.8.x to Django 1.11.x
In version 1.10.x django added this feature to allow validating required fields in the client side (HTML level) first.

https://docs.djangoproject.com/en/2.0/releases/1.10/#forms

We can always disable this but I guess moving forward that's a nice thing to have.

**Comment by johngian** [comment]
@akatsoulas @viorelaioia thoughts?

**Comment by viorelaioia** [comment]
We agreed to keep the HTML required fields validation. 
Closing this ticket, as it's not an issue.
