### ISSUE TITLE
“We're Sorry, but Something Went Wrong!” mozillians error when trying to login passwordless after upgrading to fxa

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozillians#2159]
STR:
1. Login passwordless to mozillians staging 
2. Upgrade to firefox accounts
3. Logout
4. Try to login again passwordless

Expected:
Forbidden page asking to login with most secure account (fxa) is shown

Actual:
Mozillians error page is shown

![error moz](https://user-images.githubusercontent.com/5293100/38375056-f13e5988-38fd-11e8-9580-2508537b6606.png)

**Comment by akatsoulas** [comment]
Fixed via #2160
