### ISSUE TITLE
Show usernames/id/email (or something unique to the user) when adding to groups

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozillians#2240]
Current behavior:
![image](https://user-images.githubusercontent.com/956866/39315389-641f0ad2-492b-11e8-80b2-315673dfd8c2.png)

Wanted behavior: show a unique user identifier - otherwise, one can "spoof" an account by having the same name and/or not know which one to add. I would suggest something that includes both the name, and the verified email for example (in small gray text), or something similar.

**Comment by SukhnandanMalhotra** [comment]
Hey, I am new to open source. I would like to solve this issue. Please help.
