### ISSUE TITLE
Clicking a user without a mozillians profile scrolls up to the top of the page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozillians#2270]
STR:
1. Navigate to https://web-mozillians-staging.production.paas.mozilla.community/en-US/orgchart
2. Scroll down 
3. Click any of the child elements that has no mozillians staging profile

Expected:
Nothing happens, as the user has no mozillans profile

Actual:
Scrolls up to the the top of the page

**Comment by akatsoulas** [comment]
This is fixed here:
https://github.com/mozilla/mozillians/pull/2280
