### ISSUE TITLE
bad request 400

### ISSUE THREAD

**Issue by tomahawk-pilot** [mozilla/mozillians#2358]
This error happends when we have the oauth in a container tab and the website eq. reps in another container tab. 

steps to reproduce:
1. open a site with i am in default container. 
2. open a new tab and another site and set the oauth page default to another container.
3. when the first site redirects to 0auth it opens in the container set at step 2. 
the 0auth windows pops up but the redirect doesnt work. and get a bad request 400 error.

**Comment by syam3526** [comment]
cc  @hmitsch
