### ISSUE TITLE
 UI to invite users to groups can mislead users to add the wrong users

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozillians#2390]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1391632 (this is a copy)

When adding/inviting a user to a group the UI only let you see the User's full name.
Full names are not unique, and it is not possible to add a user with 100% assurance that you're adding the correct user (in particular when several users have the same full name).
You have to first add/invite them, then load the group members, click on their name and verify it's the correct user (and if not remove them from the group).

Not ideal/may lead to security troubles.

I would propose to do something such as using the user login/email or at least displaying it in the results when you look for the person to add. Megan (mbranson) may have better suggestions though

Reproduction:
URL where this happens (for example):
https://mozillians.org/en-US/group/cis_whitelist/edit/#invitations (field: "invites")

**Comment by akatsoulas** [comment]
Relevant pr #2421 

This PR adds the email that a user is using to login next to the full name. The email will be added only for the access groups (including NDA).
