### ISSUE TITLE
not able to signup on mozillian

### ISSUE THREAD

**Issue by Anupam-dagar** [mozilla/mozillians#2397]
I tried all the methods listed there.
For the email the link which i get in mail, it says that something wrong happened.
with google, it says you should use the most secure method for your account which is github.
with github, it says to enable 2FA.

**Comment by gabru-md** [comment]
@Anupam-dagar [follow this link](https://help.github.com/articles/configuring-two-factor-authentication-via-a-totp-mobile-app/), it explains well on how to set up 2FA for your github account.
Once done, you can easily signup on mozillian using your github id.

I hope this helps!

**Comment by Anupam-dagar** [comment]
@gabru-md why google oauth doesn't work?
