### ISSUE TITLE
mozillians.org shouldnt try to internally link users

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mozillians#2403]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1466635 (public bug)

I'm not sure of how the code exactly work, feel free to close if im wrong :) @akatsoulas

**Comment by akatsoulas** [comment]
Mozillians is internally linking accounts due to the account verification process. When a user verifies a new account eg LDAP, mozillians.org needs to associate the current profile with the new email thus the account linking. @gdestuynder shall we close this issue?

**Comment by gdestuynder** [comment]
i believe that we want to stop doing that, specially for "mozillians.org repositioning"

- and by that - i mean linking (we should keep going *verification* of course) (just to be somewhat clear for other readers)

**Comment by m-branson** [comment]
>i believe that we want to stop doing that, specially for "mozillians.org repositioning"

This is what I understand to be our _future_ model and will be reflected in the architecture that I'm mapping from a proposed UX perspective now. Is this reflected in the technical architecture as well? cc @fiji-flo @hmitsch

**Comment by hmitsch** [comment]
^^ @akatsoulas @johngian

**Comment by akatsoulas** [comment]
Totally agree for the "mozillians repositioning". My suggestion to close this issue is based on the current implementation. Right now we are missing some components and I would prefer not to re-write what we have for the current stack and then once again for the new version but rather do it once. Thoughts?

**Comment by fiji-flo** [comment]
I'm still not sure what we want to build / provide to our users here. I love the idea of being able to log into Mozillians with multiple identity providers at the same time on different devices. But most of all I want something that users understand.

However, let's find a way to do this right.

For me there are two extremes:
1. We don't do any account linking or ratcheting. A person can have exactly one login method and that's it and any attempt to use another method ends up in the account creation flow. This would mean that we cannot use the email as `user_id`. And we could still allow account verification (just not via auth0).
2. We fully support account linking and have a transparent way to control this. This means all of this is owned by auth0 and users can add/remove identities as they please. I guess this too, means we should not use the email as `user_id`.
