### ISSUE TITLE
Update Open Sans to include latin-extended charset

### ISSUE THREAD

**Issue by selimsumlu** [mozilla/mozillians#2814]
The Open Sans font family currently in use doesn't include the latin-ext charset. It has been fixed in #316 but seems to be broken again at some point.

I can submit a pull request with updates files but I'm not sure if we want to include cyrillic, cyrillic-ext, greek, greek-ext and vietnamese charsets as well.

**Comment by Pike** [comment]
Just came across this with a Vietnamese name.
