### ISSUE TITLE
Add rel="me" support for external accounts

### ISSUE THREAD

**Issue by asdofindia** [mozilla/mozillians#2977]
Originally raised by David Ross [on discourse](https://discourse.mozilla.org/t/rel-me-via-mozillas-profile/33267?u=asdofindia)

We can have rel="me" links in the external accounts part of user profile. It may not be an [HTML standard](https://developer.mozilla.org/docs/Web/HTML/Link_types) but it does have wide use in [indie web](https://indieweb.org/rel-me)

Files to look at:
* https://github.com/mozilla/mozillians/blob/master/mozillians/jinja2/phonebook/profile.html
* https://github.com/mozilla/mozillians/blob/master/mozillians/phonebook/templatetags/helpers.py
* https://github.com/mozilla/mozillians/blob/master/mozillians/users/models.py

**Comment by jens1o** [comment]
I'd like to fix this, as it looks like it is an easy bug. :)

**Comment by asdofindia** [comment]
@jens1o, I think you should go ahead and make a PR.

**Comment by rugk** [comment]
Ah, I partly re-requested that in https://discourse.mozilla.org/t/mastodon-link-on-mozillians-org/34514 😄

**Comment by rugk** [comment]
IMHO this depends on https://github.com/mozilla/mozillians/issues/3207 to be useful for Mastodon, because you obviously need a link first, before you can add this attribute.

**Comment by jens1o** [comment]
I'll take a look at it on Thursday evening, before that I'm too busy. :/
