### ISSUE TITLE
User is able login with github in mozillians after adding an LDAP identity, when emails are different

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozillians#3327]
STR:
1. Login to mozillians with github 2fa, using an email address that is not mozilla
2. Add an LDAP identity through account verification => LDAP is primary identity
3. Logout 
4. Login with github again

Expected:
Forbidden error asking to login with LDAP is displayed.

Actual:
User is able to login with github.

**Comment by hmitsch** [comment]
I am deciding to close this issue in order to move ahead with _Deratcheting_ and not delay it any longer.

According to a conversation with @viorelaioia, @gdestuynder is also fine with this decision. In case the InfoSec opinion changes, we will revisit this issue.

**Comment by gdestuynder** [comment]
https://github.com/mozilla-iam/mozilla-iam/blob/master/DECISION-MAKING.md#legacy-mozilliansorg-to-be-replaced-by-dinopark-and-cis you're the boss of this module it says :)
Anyway, yes, that's fine by me. It's not perfect, but I think it's acceptable until we have Dinopark as it is a case that affect very few users (hopefully it will be zero)

**Comment by hmitsch** [comment]
Thanks, I am now going to wear that boss hat! 🎩
