### ISSUE TITLE
Unvouched users can be invited to nda group

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/mozillians#3332]
**STR:**
1. Login into mozillians prod as an nda group curator
2. Navigate to "NDA" group settings and go to invitations tab
3. Search after email "vyoioia12@gmail.com", which is not vouched, in the invitations field

**Expected:**
Email address is not displayed as an option, so he/she cannot be invited to the nda group

**Actual:**
Email address is displayed as an option, so he/she can be invited to the nda group

**Comment by hmitsch** [comment]
Note: This is *not* a blocker for the _Deratcheting_ rollout.
