### ISSUE TITLE
Leaving the NDA-STAFF group removes you from the old NDA group and other access groups

### ISSUE THREAD

**Issue by rleitan** [mozilla/mozillians#3857]
[Precondition]:
Mozillians account with MFA - login via Github with Gmail 
User is in NDA group( the old one), NDA-STAFF group and other 2 access groups ( in this order)

 STR:
1.Leave the NDA-STAFF group

[Expected result]:
The user should still be a member of the NDA group and other 2 access groups

[Actual results]:
All groups are removed (e.g. NDA, NDA-STAFF and the other 2 access groups) 

@akatsoulas

**Comment by akatsoulas** [comment]
Fixed in #3868

**Comment by rleitan** [comment]
Verified as fixed!
