### ISSUE TITLE
mozillian.org profile removing repeatedly (Fix Bug 1585611)

### ISSUE THREAD

**Issue by genialkartik** [mozilla/mozillians#3947]
I tried to create my profile on https://mozillians.org/en-US/ many times using Firefox account/Gmail Account/Github account.

Once Profile created. But after a few days, it gets deleted from the site automatically. I'm not able to locate/access my profile again. It asks me to Sign Up again. And when I set up profile again, It again gets disappear/removed. What's going wrong?

Profile once created, must be there always.
Lost my Profile again: https://mozillians.org/en-US/genialkartik

**Comment by ChiefMikeK** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1586610
