### ISSUE TITLE
Vouching claims to support Markdown, but output does not

### ISSUE THREAD

**Issue by annevk** [mozilla/mozillians#4275]
Vouching for https://mozillians.org/en-US/u/timothygu/ I wrote:
```markdown
Timothy has made numerous contributions to web standards:
* https://github.com/whatwg/url/commits?author=TimothyGu 
* https://github.com/whatwg/html/commits?author=TimothyGu
```
It seems lists are not supported, despite this indicating they are:
> Use Markdown for bold, italic, lists and links.

**Comment by gabbyprecious** [comment]
Is anyone working on this? Can I contribute to this?
